language: node_js

node_js:
  - '8'
  
branches:
    only:
        - master
  
install:
- npm install

script:
- jshint *.js

before_install: npm update -g npm

notifications:
    email:
        bob@kubrickolo.gy
